/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.Message;
import jooq.tables.records.MessageRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MessageRecord> MESSAGE__SYNTHETIC_PK_MESSAGE = Internal.createUniqueKey(Message.MESSAGE, DSL.name("SYNTHETIC_PK_message"), new TableField[] { Message.MESSAGE.ID }, true);
}
