/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.Messages;
import jooq.tables.records.MessagesRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MessagesRecord> MESSAGES__SYNTHETIC_PK_MESSAGES = Internal.createUniqueKey(Messages.MESSAGES, DSL.name("SYNTHETIC_PK_messages"), new TableField[] { Messages.MESSAGES.ID }, true);
}
