/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.Message;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>message</code>.
     */
    public static final Message MESSAGE = Message.MESSAGE;
}
