/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.Messages;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>messages</code>.
     */
    public static final Messages MESSAGES = Messages.MESSAGES;
}
