/*
 * This file is generated by jOOQ.
 */
package jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Message implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String name;
    private String message;
    private String date;

    public Message() {}

    public Message(Message value) {
        this.id = value.id;
        this.name = value.name;
        this.message = value.message;
        this.date = value.date;
    }

    public Message(
        Integer id,
        String name,
        String message,
        String date
    ) {
        this.id = id;
        this.name = name;
        this.message = message;
        this.date = date;
    }

    /**
     * Getter for <code>message.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>message.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>message.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>message.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>message.message</code>.
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * Setter for <code>message.message</code>.
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Getter for <code>message.date</code>.
     */
    public String getDate() {
        return this.date;
    }

    /**
     * Setter for <code>message.date</code>.
     */
    public void setDate(String date) {
        this.date = date;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Message other = (Message) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.message == null) {
            if (other.message != null)
                return false;
        }
        else if (!this.message.equals(other.message))
            return false;
        if (this.date == null) {
            if (other.date != null)
                return false;
        }
        else if (!this.date.equals(other.date))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.message == null) ? 0 : this.message.hashCode());
        result = prime * result + ((this.date == null) ? 0 : this.date.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Message (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(message);
        sb.append(", ").append(date);

        sb.append(")");
        return sb.toString();
    }
}
