/*
 * This file is generated by jOOQ.
 */
package jooq.tables.daos;


import java.util.List;
import java.util.Optional;

import jooq.tables.Messages;
import jooq.tables.records.MessagesRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessagesDao extends DAOImpl<MessagesRecord, jooq.tables.pojos.Messages, Integer> {

    /**
     * Create a new MessagesDao without any configuration
     */
    public MessagesDao() {
        super(Messages.MESSAGES, jooq.tables.pojos.Messages.class);
    }

    /**
     * Create a new MessagesDao with an attached configuration
     */
    public MessagesDao(Configuration configuration) {
        super(Messages.MESSAGES, jooq.tables.pojos.Messages.class, configuration);
    }

    @Override
    public Integer getId(jooq.tables.pojos.Messages object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Messages> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Messages.MESSAGES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<jooq.tables.pojos.Messages> fetchById(Integer... values) {
        return fetch(Messages.MESSAGES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public jooq.tables.pojos.Messages fetchOneById(Integer value) {
        return fetchOne(Messages.MESSAGES.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<jooq.tables.pojos.Messages> fetchOptionalById(Integer value) {
        return fetchOptional(Messages.MESSAGES.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Messages> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Messages.MESSAGES.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<jooq.tables.pojos.Messages> fetchByName(String... values) {
        return fetch(Messages.MESSAGES.NAME, values);
    }

    /**
     * Fetch records that have <code>message BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Messages> fetchRangeOfMessage(String lowerInclusive, String upperInclusive) {
        return fetchRange(Messages.MESSAGES.MESSAGE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>message IN (values)</code>
     */
    public List<jooq.tables.pojos.Messages> fetchByMessage(String... values) {
        return fetch(Messages.MESSAGES.MESSAGE, values);
    }

    /**
     * Fetch records that have <code>date BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<jooq.tables.pojos.Messages> fetchRangeOfDate(String lowerInclusive, String upperInclusive) {
        return fetchRange(Messages.MESSAGES.DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>date IN (values)</code>
     */
    public List<jooq.tables.pojos.Messages> fetchByDate(String... values) {
        return fetch(Messages.MESSAGES.DATE, values);
    }
}
